<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(RepositoryRoot)eng/Maui.props" />

  <PropertyGroup>
    <TargetFramework>$(DotNetTfm)</TargetFramework>
    <IsTizenProject>false</IsTizenProject>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Maui.Tizen.Controls.RefPackCompile/Maui.Tizen.Controls.RefPackCompile.csproj" />
    <PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="Microsoft.Maui.Core" />
  </ItemGroup>

</Project>
