using System.Text.Json;
using System.Text.Json.Serialization;

namespace Maui.Tizen.SourceTests;

public sealed record ParityMapper(string Key, string Method, string Status, string? Reason);

public sealed record ParityHandler(
	string Handler,
	string BaseType,
	string File,
	string? NeutralHandler,
	IReadOnlyList<ParityMapper> PropertyMappers,
	IReadOnlyList<ParityMapper> CommandMappers,
	IReadOnlyList<string> UncoveredNeutralKeys);

public sealed record ParityDocument(string Wave, string Description, IReadOnlyList<ParityHandler> Handlers);

public class MapperParityTests
{
	const string ManifestRelativePath = "docs/wave-b-mapper-parity.json";

	static readonly JsonSerializerOptions Json = new()
	{
		WriteIndented = true,
		DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
	};

	/// <summary>Builds the parity view from source plus reflection over the real MAUI assemblies.</summary>
	static ParityDocument Build()
	{
		var handlers = new List<ParityHandler>();

		foreach (var handler in WaveBSource.Handlers)
		{
			var neutralName = handler.TypeName["Tizen".Length..];
			var neutral = NeutralMaui.FindHandler(neutralName);
			var neutralKeys = neutral is null
				? Array.Empty<string>()
				: NeutralMaui.MapperKeys(neutral, "Mapper").ToArray();

			var implemented = ImplementedKeys(handler);

			// Keys the shared view/element mapper already supplies are inherited by chaining.
			var uncovered = neutralKeys
				.Where(k => !implemented.Contains(k))
				.Where(k => !NeutralMaui.ViewMapperKeys.Contains(k))
				.Distinct(StringComparer.Ordinal)
				.OrderBy(k => k, StringComparer.Ordinal)
				.ToList();

			handlers.Add(new ParityHandler(
				handler.TypeName,
				handler.BaseType,
				handler.RelativePath,
				neutralKeys.Length > 0 ? neutral!.FullName : null,
				handler.PropertyMappers.Select(Convert).ToList(),
				handler.CommandMappers.Select(Convert).ToList(),
				uncovered));
		}

		return new ParityDocument(
			"B",
			"Mapper parity for the Wave B Tizen handlers. Generated by Maui.Tizen.SourceTests; " +
			"regenerate with MAUI_TIZEN_UPDATE_PARITY=1 dotnet test.",
			handlers);
	}

	static ParityMapper Convert(MapperEntry entry) =>
		new(entry.Key, entry.Method, entry.Status, entry.IsNoOp ? entry.Reason : null);

	/// <summary>
	/// Keys a handler covers, including those inherited by chaining onto a migrated base handler's
	/// mapper (for example the shape handlers chaining <c>TizenShapeViewHandler.Mapper</c>).
	/// </summary>
	static HashSet<string> ImplementedKeys(HandlerSource handler)
	{
		var keys = handler.PropertyMappers.Select(m => m.Key)
			.Concat(handler.CommandMappers.Select(m => m.Key))
			.ToHashSet(StringComparer.Ordinal);

		var baseHandler = WaveBSource.Handlers.FirstOrDefault(h => h.TypeName == handler.BaseType);

		if (baseHandler is not null && baseHandler.TypeName != handler.TypeName)
		{
			keys.UnionWith(ImplementedKeys(baseHandler));
		}

		return keys;
	}

	/// <summary>
	/// The manifest is generated, not hand-maintained, so it cannot drift from the source it
	/// describes. Set MAUI_TIZEN_UPDATE_PARITY=1 to rewrite it after intentional changes.
	/// </summary>
	[Fact]
	public void ParityManifestMatchesSource()
	{
		var path = RepoPaths.Combine(ManifestRelativePath.Split('/'));
		var expected = JsonSerializer.Serialize(Build(), Json) + Environment.NewLine;

		if (Environment.GetEnvironmentVariable("MAUI_TIZEN_UPDATE_PARITY") == "1")
		{
			Directory.CreateDirectory(Path.GetDirectoryName(path)!);
			File.WriteAllText(path, expected);
		}

		Assert.True(File.Exists(path), $"{ManifestRelativePath} is missing. Regenerate with MAUI_TIZEN_UPDATE_PARITY=1.");
		Assert.Equal(expected.ReplaceLineEndings(), File.ReadAllText(path).ReplaceLineEndings());
	}

	/// <summary>
	/// Every mapper key the neutral MAUI handler declares must either be implemented here or show up
	/// as a recorded gap. This is the check that keeps the port honest as MAUI adds properties.
	/// </summary>
	[Fact]
	public void EveryNeutralMapperKeyIsImplementedOrRecorded()
	{
		var document = Build();
		var recorded = LoadRecordedGaps();
		var failures = new List<string>();

		foreach (var handler in document.Handlers)
		{
			foreach (var key in handler.UncoveredNeutralKeys)
			{
				if (!recorded.TryGetValue(handler.Handler, out var keys) || !keys.Contains(key))
				{
					failures.Add($"{handler.Handler} does not map '{key}' and it is not recorded in {ManifestRelativePath}.");
				}
			}
		}

		Assert.Empty(failures);
	}

	/// <summary>An empty mapper body is only acceptable when the reason is documented in the source.</summary>
	[Fact]
	public void EveryNoOpMapperDocumentsWhy()
	{
		var failures = new List<string>();

		foreach (var handler in WaveBSource.Handlers)
		{
			foreach (var entry in handler.PropertyMappers.Concat(handler.CommandMappers))
			{
				if (entry.IsNoOp && string.IsNullOrWhiteSpace(entry.Reason))
				{
					failures.Add($"{handler.TypeName}.{entry.Method} is a no-op with no documented reason ({handler.RelativePath}).");
				}
			}
		}

		Assert.Empty(failures);
	}

	/// <summary>Each migrated handler must expose the standard three-constructor mapper surface.</summary>
	[Fact]
	public void EveryHandlerWithMappersDeclaresBothMappers()
	{
		var failures = WaveBSource.Handlers
			.Where(h => h.PropertyMappers.Count > 0)
			.Where(h => !File.ReadAllText(RepoPaths.Combine(h.RelativePath.Split('/'))).Contains("CommandMapper"))
			.Select(h => h.TypeName)
			.ToList();

		Assert.Empty(failures);
	}

	static Dictionary<string, HashSet<string>> LoadRecordedGaps()
	{
		var path = RepoPaths.Combine(ManifestRelativePath.Split('/'));

		if (!File.Exists(path))
		{
			return new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
		}

		var document = JsonSerializer.Deserialize<ParityDocument>(File.ReadAllText(path), Json);

		return document?.Handlers.ToDictionary(
			h => h.Handler,
			h => h.UncoveredNeutralKeys.ToHashSet(StringComparer.Ordinal),
			StringComparer.Ordinal) ?? new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
	}
}
