using System.Text.Json;
using System.Text.Json.Serialization;

namespace Maui.Tizen.SourceTests;

/// <summary>
/// Mapper parity for the Wave C handlers.
/// </summary>
/// <remarks>
/// Mirrors <see cref="MapperParityTests"/> for Wave B, and reuses the same generated-manifest
/// approach: the artifact is produced from source rather than hand-written, so it cannot quietly
/// disagree with the code it claims to describe.
/// </remarks>
public class WaveCMapperParityTests
{
	const string ManifestRelativePath = "docs/wave-c-mapper-parity.json";

	static readonly JsonSerializerOptions Json = new()
	{
		WriteIndented = true,
		DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
	};

	static ParityDocument Build()
	{
		var handlers = new List<ParityHandler>();

		foreach (var handler in WaveCSource.Handlers)
		{
			// TizenCollectionViewHandler -> CollectionViewHandler. Generic handlers keep their
			// arity in the source name (TizenItemsViewHandler), which matches the neutral name.
			var neutralName = handler.TypeName["Tizen".Length..];
			var neutral = NeutralMaui.FindHandler(neutralName);
			var neutralKeys = neutral is null
				? Array.Empty<string>()
				: NeutralMaui.MapperKeys(neutral, "Mapper").ToArray();

			var implemented = ImplementedKeys(handler);

			var uncovered = neutralKeys
				.Where(k => !implemented.Contains(k))
				.Where(k => !NeutralMaui.ViewMapperKeys.Contains(k))
				.Distinct(StringComparer.Ordinal)
				.OrderBy(k => k, StringComparer.Ordinal)
				.ToList();

			handlers.Add(new ParityHandler(
				handler.TypeName,
				handler.BaseType,
				handler.RelativePath,
				neutralKeys.Length > 0 ? neutral!.FullName : null,
				handler.PropertyMappers.Select(Convert).ToList(),
				handler.CommandMappers.Select(Convert).ToList(),
				uncovered));
		}

		return new ParityDocument(
			"C",
			"Mapper parity for the Wave C Tizen handlers: navigation, Shell, CollectionView, " +
			"toolbar and menus. Generated by Maui.Tizen.SourceTests; regenerate with " +
			"MAUI_TIZEN_UPDATE_PARITY=1 dotnet test.",
			handlers);
	}

	static ParityMapper Convert(MapperEntry entry) =>
		new(entry.Key, entry.Method, entry.Status, entry.IsNoOp ? entry.Reason : null);

	static HashSet<string> ImplementedKeys(HandlerSource handler)
	{
		var keys = handler.PropertyMappers.Select(m => m.Key)
			.Concat(handler.CommandMappers.Select(m => m.Key))
			.ToHashSet(StringComparer.Ordinal);

		// Generic base handlers appear as "TizenStructuredItemsViewHandler<TItemsView>" in a base
		// list, so compare on the unqualified, un-parameterised name.
		var baseName = StripGenericArity(handler.BaseType);

		var baseHandler = WaveCSource.Handlers
			.FirstOrDefault(h => StripGenericArity(h.TypeName) == baseName);

		if (baseHandler is not null && baseHandler.TypeName != handler.TypeName)
		{
			keys.UnionWith(ImplementedKeys(baseHandler));
		}

		return keys;
	}

	static string StripGenericArity(string typeName)
	{
		var index = typeName.IndexOf('<', StringComparison.Ordinal);
		return index < 0 ? typeName : typeName[..index];
	}

	[Fact]
	public void WaveCSourcesWereDiscovered()
	{
		Assert.NotEmpty(WaveCSource.Files);
		Assert.NotEmpty(WaveCSource.Handlers);
	}

	/// <summary>
	/// The manifest is generated, not hand-maintained. Set MAUI_TIZEN_UPDATE_PARITY=1 to rewrite it
	/// after an intentional change.
	/// </summary>
	[Fact]
	public void ParityManifestMatchesSource()
	{
		var path = RepoPaths.Combine(ManifestRelativePath.Split('/'));
		var expected = JsonSerializer.Serialize(Build(), Json) + Environment.NewLine;

		if (Environment.GetEnvironmentVariable("MAUI_TIZEN_UPDATE_PARITY") == "1")
		{
			Directory.CreateDirectory(Path.GetDirectoryName(path)!);
			File.WriteAllText(path, expected);
		}

		Assert.True(File.Exists(path), $"{ManifestRelativePath} is missing. Regenerate with MAUI_TIZEN_UPDATE_PARITY=1.");
		Assert.Equal(expected.ReplaceLineEndings(), File.ReadAllText(path).ReplaceLineEndings());
	}

	/// <summary>
	/// Every key the neutral MAUI handler declares is either implemented by the Tizen handler or
	/// recorded as an explicit gap. This is what stops the port from silently falling behind as
	/// MAUI adds properties.
	/// </summary>
	[Fact]
	public void EveryNeutralMapperKeyIsImplementedOrRecorded()
	{
		var document = Build();
		var recorded = LoadRecordedGaps();
		var failures = new List<string>();

		foreach (var handler in document.Handlers)
		{
			foreach (var key in handler.UncoveredNeutralKeys)
			{
				if (!recorded.TryGetValue(handler.Handler, out var keys) || !keys.Contains(key))
				{
					failures.Add($"{handler.Handler} does not map '{key}' and it is not recorded in {ManifestRelativePath}.");
				}
			}
		}

		Assert.Empty(failures);
	}

	/// <summary>
	/// A no-op mapper without a documented reason is indistinguishable from an unfinished one.
	/// </summary>
	[Fact]
	public void EveryNoOpMapperDocumentsWhy()
	{
		var failures = WaveCSource.Handlers
			.SelectMany(h => h.PropertyMappers.Concat(h.CommandMappers).Select(m => (Handler: h, Mapper: m)))
			.Where(x => x.Mapper.IsNoOp && string.IsNullOrWhiteSpace(x.Mapper.Reason))
			.Select(x => $"{x.Handler.TypeName}.{x.Mapper.Key} is an empty no-op with no XML doc explaining why.")
			.ToList();

		Assert.Empty(failures);
	}

	/// <summary>
	/// A handler with a property mapper but no command mapper silently drops every command -
	/// <c>RequestNavigation</c> among them - instead of failing.
	/// </summary>
	[Fact]
	public void EveryHandlerWithMappersDeclaresBothMappers()
	{
		var failures = WaveCSource.Handlers
			.Where(h => h.PropertyMappers.Count > 0)
			.Where(h => !File.ReadAllText(RepoPaths.Combine(h.RelativePath.Split('/'))).Contains("CommandMapper"))
			.Select(h => h.TypeName)
			.ToList();

		Assert.Empty(failures);
	}

	static Dictionary<string, HashSet<string>> LoadRecordedGaps()
	{
		var path = RepoPaths.Combine(ManifestRelativePath.Split('/'));

		if (!File.Exists(path))
		{
			return new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
		}

		var document = JsonSerializer.Deserialize<ParityDocument>(File.ReadAllText(path), Json);

		return document?.Handlers.ToDictionary(
			h => h.Handler,
			h => h.UncoveredNeutralKeys.ToHashSet(StringComparer.Ordinal),
			StringComparer.Ordinal) ?? new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
	}
}
