using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Maui.Tizen.SourceTests;

/// <summary>
/// Mapper parity for the Wave C handlers.
/// </summary>
/// <remarks>
/// Mirrors <see cref="MapperParityTests"/> for Wave B, and reuses the same generated-manifest
/// approach: the artifact is produced from source rather than hand-written, so it cannot quietly
/// disagree with the code it claims to describe.
/// </remarks>
public class WaveCMapperParityTests
{
	const string ManifestRelativePath = "docs/wave-c-mapper-parity.json";
	const string MarkdownRelativePath = "docs/wave-c-mapper-parity.md";

	static readonly JsonSerializerOptions Json = new()
	{
		WriteIndented = true,
		DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
	};

	static ParityDocument Build()
	{
		var handlers = new List<ParityHandler>();

		foreach (var handler in WaveCSource.Handlers)
		{
			// TizenCollectionViewHandler -> CollectionViewHandler. Generic handlers keep their
			// arity in the source name (TizenItemsViewHandler), which matches the neutral name.
			var neutralName = handler.TypeName["Tizen".Length..];
			var neutral = NeutralMaui.FindHandler(neutralName);
			var neutralKeys = neutral is null
				? Array.Empty<string>()
				: NeutralMaui.MapperKeys(neutral, "Mapper").ToArray();

			var implemented = ImplementedKeys(handler);

			var uncovered = neutralKeys
				.Where(k => !implemented.Contains(k))
				.Where(k => !NeutralMaui.ViewMapperKeys.Contains(k))
				.Distinct(StringComparer.Ordinal)
				.OrderBy(k => k, StringComparer.Ordinal)
				.ToList();

			handlers.Add(new ParityHandler(
				handler.TypeName,
				handler.BaseType,
				handler.RelativePath,
				neutralKeys.Length > 0 ? neutral!.FullName : null,
				handler.PropertyMappers.Select(Convert).ToList(),
				handler.CommandMappers.Select(Convert).ToList(),
				uncovered));
		}

		return new ParityDocument(
			"C",
			"Mapper parity for the Wave C Tizen handlers: navigation, Shell, CollectionView, " +
			"toolbar and menus. Generated by Maui.Tizen.SourceTests; regenerate with " +
			"MAUI_TIZEN_UPDATE_PARITY=1 dotnet test.",
			handlers);
	}

	static ParityMapper Convert(MapperEntry entry) =>
		new(entry.Key, entry.Method, entry.Status, entry.IsNoOp ? entry.Reason : null);

	static string BuildMarkdown(ParityDocument document)
	{
		var mappings = document.Handlers
			.SelectMany(handler => handler.PropertyMappers.Concat(handler.CommandMappers))
			.ToList();
		var builder = new System.Text.StringBuilder();

		builder.AppendLine("# Wave C mapper parity");
		builder.AppendLine();
		builder.AppendLine("Companion to [`wave-c-mapper-parity.json`](wave-c-mapper-parity.json), generated deterministically");
		builder.AppendLine("from the current Wave C source by `Maui.Tizen.SourceTests`. Regenerate the JSON with:");
		builder.AppendLine();
		builder.AppendLine("```bash");
		builder.AppendLine("MAUI_TIZEN_UPDATE_PARITY=1 dotnet test tests/Maui.Tizen.SourceTests/Maui.Tizen.SourceTests.csproj");
		builder.AppendLine("```");
		builder.AppendLine();
		builder.AppendLine("## Summary");
		builder.AppendLine();
		builder.AppendLine($"- {document.Handlers.Count} migrated handlers");
		builder.AppendLine($"- {mappings.Count(mapper => mapper.Status == "Supported")} supported mappings, {mappings.Count(mapper => mapper.Status == "NoOp")} documented no-ops");
		builder.AppendLine($"- {document.Handlers.Count(handler => handler.UncoveredNeutralKeys.Count > 0)} handlers with recorded neutral-key gaps");
		builder.AppendLine();
		builder.AppendLine("`UncoveredNeutralKeys` are recorded gaps, not silent omissions. The source tests fail when the");
		builder.AppendLine("current MAUI mapper surface and this manifest differ.");
		builder.AppendLine();
		builder.AppendLine("## Handlers");
		builder.AppendLine();

		foreach (var handler in document.Handlers)
		{
			builder.AppendLine($"### `{handler.Handler}`");
			builder.AppendLine();
			builder.AppendLine($"- Source: `{handler.File}`");
			builder.AppendLine($"- Base: `{handler.BaseType}`");
			if (handler.NeutralHandler is not null)
				builder.AppendLine($"- Neutral counterpart: `{handler.NeutralHandler}`");
			builder.AppendLine();

			AppendMappers(builder, "Property mappers", handler.PropertyMappers);
			AppendMappers(builder, "Command mappers", handler.CommandMappers);

			if (handler.UncoveredNeutralKeys.Count > 0)
			{
				builder.AppendLine(
					"**Recorded gaps:** "
					+ string.Join(", ", handler.UncoveredNeutralKeys.Select(key => $"`{key}`")));
				builder.AppendLine();
			}
		}

		return builder.ToString();
	}

	static void AppendMappers(
		System.Text.StringBuilder builder,
		string title,
		IReadOnlyList<ParityMapper> mappings)
	{
		if (mappings.Count == 0)
			return;

		builder.AppendLine($"**{title}**");
		builder.AppendLine();
		builder.AppendLine("| Key | Method | Status | Notes |");
		builder.AppendLine("| --- | --- | --- | --- |");
		foreach (var mapper in mappings)
		{
			var reason = (mapper.Reason ?? string.Empty)
				.Replace("|", "\\|", StringComparison.Ordinal)
				.ReplaceLineEndings(" ");
			builder.AppendLine($"| `{mapper.Key}` | `{mapper.Method}` | {mapper.Status} | {reason} |");
		}
		builder.AppendLine();
	}

	static HashSet<string> ImplementedKeys(HandlerSource handler)
	{
		var keys = handler.PropertyMappers.Select(m => m.Key)
			.Concat(handler.CommandMappers.Select(m => m.Key))
			.ToHashSet(StringComparer.Ordinal);

		// Generic base handlers appear as "TizenStructuredItemsViewHandler<TItemsView>" in a base
		// list, so compare on the unqualified, un-parameterised name.
		var baseName = StripGenericArity(handler.BaseType);

		var baseHandler = WaveCSource.Handlers
			.FirstOrDefault(h => StripGenericArity(h.TypeName) == baseName);

		if (baseHandler is not null && baseHandler.TypeName != handler.TypeName)
		{
			keys.UnionWith(ImplementedKeys(baseHandler));
		}

		return keys;
	}

	static string StripGenericArity(string typeName)
	{
		var index = typeName.IndexOf('<', StringComparison.Ordinal);
		return index < 0 ? typeName : typeName[..index];
	}

	[Fact]
	public void WaveCSourcesWereDiscovered()
	{
		Assert.NotEmpty(WaveCSource.Files);
		Assert.NotEmpty(WaveCSource.Handlers);
	}

	/// <summary>
	/// The manifest is generated, not hand-maintained. Set MAUI_TIZEN_UPDATE_PARITY=1 to rewrite it
	/// after an intentional change.
	/// </summary>
	[Fact]
	public void ParityManifestMatchesSource()
	{
		var path = RepoPaths.Combine(ManifestRelativePath.Split('/'));
		var markdownPath = RepoPaths.Combine(MarkdownRelativePath.Split('/'));
		var document = Build();
		var expected = JsonSerializer.Serialize(document, Json) + Environment.NewLine;
		var expectedMarkdown = BuildMarkdown(document);

		if (Environment.GetEnvironmentVariable("MAUI_TIZEN_UPDATE_PARITY") == "1")
		{
			Directory.CreateDirectory(Path.GetDirectoryName(path)!);
			File.WriteAllText(path, expected);
			File.WriteAllText(markdownPath, expectedMarkdown);
		}

		Assert.True(File.Exists(path), $"{ManifestRelativePath} is missing. Regenerate with MAUI_TIZEN_UPDATE_PARITY=1.");
		Assert.Equal(expected.ReplaceLineEndings(), File.ReadAllText(path).ReplaceLineEndings());
		Assert.True(File.Exists(markdownPath), $"{MarkdownRelativePath} is missing. Regenerate with MAUI_TIZEN_UPDATE_PARITY=1.");
		Assert.Equal(expectedMarkdown.ReplaceLineEndings(), File.ReadAllText(markdownPath).ReplaceLineEndings());
	}

	/// <summary>
	/// Every key the neutral MAUI handler declares is either implemented by the Tizen handler or
	/// recorded as an explicit gap. This is what stops the port from silently falling behind as
	/// MAUI adds properties.
	/// </summary>
	[Fact]
	public void EveryNeutralMapperKeyIsImplementedOrRecorded()
	{
		var document = Build();
		var recorded = LoadRecordedGaps();
		var failures = new List<string>();

		foreach (var handler in document.Handlers)
		{
			foreach (var key in handler.UncoveredNeutralKeys)
			{
				if (!recorded.TryGetValue(handler.Handler, out var keys) || !keys.Contains(key))
				{
					failures.Add($"{handler.Handler} does not map '{key}' and it is not recorded in {ManifestRelativePath}.");
				}
			}
		}

		Assert.Empty(failures);
	}

	/// <summary>
	/// A no-op mapper without a documented reason is indistinguishable from an unfinished one.
	/// </summary>
	[Fact]
	public void EveryNoOpMapperDocumentsWhy()
	{
		var failures = WaveCSource.Handlers
			.SelectMany(h => h.PropertyMappers.Concat(h.CommandMappers).Select(m => (Handler: h, Mapper: m)))
			.Where(x => x.Mapper.IsNoOp && string.IsNullOrWhiteSpace(x.Mapper.Reason))
			.Select(x => $"{x.Handler.TypeName}.{x.Mapper.Key} is an empty no-op with no XML doc explaining why.")
			.ToList();

		Assert.Empty(failures);
	}

	/// <summary>
	/// A handler with a property mapper but no command mapper silently drops every command -
	/// <c>RequestNavigation</c> among them - instead of failing.
	/// </summary>
	[Fact]
	public void EveryHandlerWithMappersDeclaresBothMappers()
	{
		var failures = WaveCSource.Handlers
			.Where(h => h.PropertyMappers.Count > 0)
			.Where(h => !File.ReadAllText(RepoPaths.Combine(h.RelativePath.Split('/'))).Contains("CommandMapper"))
			.Select(h => h.TypeName)
			.ToList();

		Assert.Empty(failures);
	}

	static Dictionary<string, HashSet<string>> LoadRecordedGaps()
	{
		var path = RepoPaths.Combine(ManifestRelativePath.Split('/'));

		if (!File.Exists(path))
		{
			return new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
		}

		var document = JsonSerializer.Deserialize<ParityDocument>(File.ReadAllText(path), Json);

		return document?.Handlers.ToDictionary(
			h => h.Handler,
			h => h.UncoveredNeutralKeys.ToHashSet(StringComparer.Ordinal),
			StringComparer.Ordinal) ?? new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
	}

	/// <summary>
	/// A no-op justification must be specific to the feature it is refusing to implement.
	/// </summary>
	/// <remarks>
	/// <c>EveryNoOpMapperDocumentsWhy</c> only proves a comment exists. Thirty mappers all saying
	/// "not supported on Tizen" would pass it while telling a reviewer nothing. This requires each
	/// reason to actually name the thing it is about, so the parity artifact stays reviewable.
	/// </remarks>
	[Fact]
	public void EveryNoOpJustificationIsFeatureSpecific()
	{
		var failures = new List<string>();

		foreach (var handler in WaveCSource.Handlers)
		{
			foreach (var mapper in handler.PropertyMappers.Concat(handler.CommandMappers).Where(m => m.IsNoOp))
			{
				var reason = mapper.Reason ?? string.Empty;

				// The reason has to mention the property it is about, or explain the platform
				// limitation in enough words to be meaningful - not just assert one exists.
				var namesTheFeature = reason.Contains(mapper.Key, StringComparison.OrdinalIgnoreCase);
				var wordCount = reason.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length;

				if (!namesTheFeature && wordCount < 12)
				{
					failures.Add($"{handler.TypeName}.{mapper.Key}: \"{reason}\" is too generic - name the "
						+ "property or explain the specific Tizen limitation.");
				}
			}
		}

		Assert.Empty(failures);
	}

	/// <summary>
	/// The TabbedPage badge mappers from dotnet/maui#37755 must stay declared and classified.
	/// </summary>
	[Fact]
	public void TabbedPageBadgeMappersAreDeclaredAndClassified()
	{
		var tabbed = WaveCSource.Handlers.SingleOrDefault(h => h.TypeName == "TizenTabbedPageHandler");

		Assert.NotNull(tabbed);

		foreach (var key in new[] { "BadgeText", "BadgeColor", "BadgeTextColor" })
		{
			var mapper = tabbed!.PropertyMappers.SingleOrDefault(m => m.Key == key);

			Assert.True(mapper is not null, $"TizenTabbedPageHandler must map '{key}' (dotnet/maui#37755).");
			Assert.True(mapper!.IsNoOp, $"'{key}' is expected to be an explicit no-op on Tizen.");
			Assert.False(string.IsNullOrWhiteSpace(mapper.Reason), $"'{key}' needs a documented reason.");
		}
	}


	/// <summary>
	/// The Controls-level mapper remaps must have run before any neutral mapper is read.
	/// </summary>
	/// <remarks>
	/// Neutral mappers are mutated at runtime: <c>FlyoutPage.RemapForControls()</c> adds
	/// <c>FlyoutLayoutBehavior</c> to the static <c>FlyoutViewHandler.Mapper</c> when a Controls host
	/// is built. Without forcing that first, the generated parity manifest depends on test ORDER -
	/// which is exactly how it came to disagree between a local run and CI on the same commit.
	/// <para>
	/// This asserts the forcing in <c>NeutralMaui</c> actually worked, rather than having silently
	/// swallowed an exception and left the neutral key set half-populated.
	/// </para>
	/// </remarks>
	[Fact]
	public void ControlsRemapsAreDeterministic()
	{
		ControlsHost.EnsureBuilt();
		var flyout = NeutralMaui.FindHandler("FlyoutViewHandler");

		Assert.NotNull(flyout);

		var keys = NeutralMaui.MapperKeys(flyout!, "Mapper");

		Assert.Contains("FlyoutLayoutBehavior", keys);
	}


	/// <summary>
	/// Every captured mapper snapshot must equal the live shared mapper, read independently.
	/// </summary>
	/// <remarks>
	/// <para>
	/// <see cref="ControlsRemapsAreDeterministic"/> proves the remaps ran; this proves the SNAPSHOTS
	/// were taken afterwards. They are different failures. A static field initializer runs before a
	/// static constructor body, so a snapshot can be stale even though the remaps later succeeded -
	/// which is exactly what happened here: the suite passed only because an earlier test had
	/// already initialized Controls, and failed alone in a fresh process with false BackgroundColor
	/// gaps.
	/// </para>
	/// <para>
	/// The live side is read through raw reflection rather than through <c>NeutralMaui.MapperKeys</c>
	/// ON PURPOSE. An earlier version of this test compared the snapshot against a helper that
	/// itself forces the remaps, so BOTH sides went stale together and the test passed even with the
	/// guard removed - verified by removing it. Reading the mapper directly keeps the two sides
	/// genuinely independent.
	/// </para>
	/// </remarks>
	[Fact]
	public void CapturedMapperSnapshotsMatchTheLiveSharedMapper()
	{
		// Capture the snapshot FIRST, exactly as a consumer would, then force the remaps and read
		// the mapper again. If the snapshot was taken too early it will now be visibly short.
		//
		// Ordering matters: an earlier version read the live side through a helper that itself
		// forces the remaps, so both sides went stale together and the test passed even with the
		// guard removed - verified by removing it.
		var snapshot = NeutralMaui.ViewMapperKeys;

		ControlsHost.EnsureBuilt();

		var viewHandler = NeutralMaui.Core.GetExportedTypes()
			.First(t => t.FullName == "Microsoft.Maui.Handlers.ViewHandler");

		var mapper = viewHandler
			.GetField("ViewMapper", BindingFlags.Public | BindingFlags.Static)!
			.GetValue(null)!;

		var live = ((System.Collections.IEnumerable)mapper.GetType()
				.GetMethod("GetKeys")!
				.Invoke(mapper, null)!)
			.Cast<string>()
			.ToHashSet(StringComparer.Ordinal);

		var missing = live.Where(k => !snapshot.Contains(k))
			.OrderBy(k => k, StringComparer.Ordinal)
			.ToList();

		Assert.True(
			missing.Count == 0,
			"The cached view-mapper snapshot is missing keys the live mapper has (" + string.Join(", ", missing)
				+ "), so it was captured before the Controls remaps ran. Make every mapper-derived "
				+ "value in NeutralMaui lazy and route it through EnsureRemapsBeforeReadingMappers().");
	}

	/// <summary>
	/// The shared view-mapper snapshot must contain the Controls-level keys.
	/// </summary>
	/// <remarks>
	/// Stated positively as well as relatively, so the check cannot pass by both sides being
	/// equally stale.
	/// </remarks>
	[Fact]
	public void TheSharedViewMapperSnapshotIncludesControlsLevelKeys()
	{
		Assert.Contains("BackgroundColor", NeutralMaui.ViewMapperKeys);
		Assert.Contains("IsInAccessibleTree", NeutralMaui.ViewMapperKeys);
	}

}
